### ISSUE TITLE
Invalid VCard PHOTO TYPE

### ISSUE THREAD

**Issue by ManOki** [owncloud/contacts#425]
### Steps to reproduce
1. create a contact
2. upload any jpg image as photo
3. export vcf using contacts download button (via settings down-left)
4. open vcf with an editor
### Expected behaviour

the photo section of the contact should look like `PHOTO;ENCODING=B;TYPE=JPEG:/9j/4AAQSkZJRg`
### Actual behaviour

the photo section looks like `PHOTO;TYPE=image/jpeg:/9j/4AAQSkZJRg`
### Server configuration

**Operating system**: Debian Jessie

**Web server:** Apache 2.4

**Database:** Maria-DB 10.2

**PHP version:** 5.6.20

**ownCloud version:** 9.0.2

**Contacts version:** 1.3.1.0

**Updated from an older ownCloud or fresh install:** tested both, doesn't matter

**Signing status (ownCloud 9.0 and above):** all valid

**List of activated apps:**

```
Enabled:                       
  - activity: 2.2.1            
  - announcementcenter: 1.1.2  
  - bookmarks: 0.7
  - calendar: 1.2.2            
  - comments: 0.2              
  - contacts: 1.3.1.0          
  - dav: 0.1.6                 
  - direct_menu: 0.7.1         
  - documents: 0.12.0          
  - external: 1.2              
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4          
  - files: 1.4.4               
  - files_external: 0.5.2      
  - files_pdfviewer: 0.8.1     
  - files_sharing: 0.9.1       
  - files_texteditor: 2.1      
  - files_trashbin: 0.8.0      
  - files_versions: 1.2.0      
  - files_videoplayer: 0.9.8   
  - gallery: 14.5.0            
  - mail: 0.5.1                
  - music: 0.3.11              
  - news: 8.8.0                
  - notifications: 0.2.3       
  - ownnote: 1.08              
  - provisioning_api: 0.4.1    
  - systemtags: 0.2            
  - tasks: 0.9.1               
  - templateeditor: 0.1        
Disabled:                      
  - encryption                 
  - firstrunwizard             
  - updatenotification         
  - user_external              
  - user_ldap                  
```
